#lang racket

(require "../main.rkt")

;; main riff from "Smoke on the Water", by Deep Purple
(emit (mix (list (sequence 1 (list (chord 'D 3 1 'custom 0 5)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 3 8)
                                   '(#f . 1)
                                   (chord 'D 3 2 'custom 5 10)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 0 5)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 3 8)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 6 11)
                                   (chord 'D 3 2 'custom 5 10)
                                   '(#f . 2)
                                   
                                   (chord 'D 3 1 'custom 0 5)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 3 8)
                                   '(#f . 1)
                                   (chord 'D 3 2 'custom 5 10)
                                   '(#f . 1)
                                   (chord 'D 3 1 'custom 3 8)
                                   '(#f . 1)
                                   (chord 'D 3 5 'custom 0 5))
                           224 sawtooth-wave)
                 1)
           (list (drum 2 '(O #f X #f O #f X #f O #f X #f O O X X) 224)
                 1))
      "smoke-on-the-water.wav")
